# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /norm-fullstack

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# API key - this will be passed at runtime
ENV OPENAI_API_KEY=$OPENAI_API_KEY

# Copy the content of the local directories to the working directory
COPY ./app /norm-fullstack/app
COPY ./docs /norm-fullstack/docs
COPY ./test_utils.py /norm-fullstack/test_utils.py

# Command to run the test script
CMD ["python", "test_utils.py"]